knex: # knex options get imported to knexfile.js to be able to use knex command line client
  client: mysql
  debug: false
  connection:
    host: localhost
    database: event
    user: event
    password: event
  timezone: UTC
  migrations:
    directory: ./sql/migrations
    tableName: knex_migrations