knex: # knex options get imported to knexfile.js to be able to use knex command line client
  client: sqlite3
  debug: true
  connection:
    filename: testing.db
  timezone: UTC
  migrations:
    directory: ./sql/migrations
    tableName: knex_migrations