knex:
  client: mysql2
  debug: false
  connection:
    host: localhost
    port: 33006
    database: event
    user: event
    password: event
  timezone: UTC
  migrations:
    directory: ./sql/migrations
    tableName: knex_migrations_files
  seeds:
    directory: ./sql/seeds

messageQueue:
  url: amqp://localhost
  port: 5672
  name: converted_files