database:
  host: localhost
  user: 
  password: 
  database: event
  connectionLimit: 30
  debug: false

messageQueue:
  url: amqp://localhost
  port: 5672
  uploadFinishedQueue: uploaded

convert:
  outputPath: 'public'